# Generated by Django 5.0 on 2023-12-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenancemodel_machine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancemodel',
            old_name='order_data',
            new_name='order_date',
        ),
    ]
