# Generated by Django 5.0 on 2023-12-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0003_alter_servicecompany_user'),
        ('machine', '0004_rename_machine_machinemodel'),
        ('maintenance', '0003_remove_maintenance_work_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maintenance',
            new_name='MaintenanceModel',
        ),
    ]
