# Generated by Django 5.0 on 2023-12-24 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handbooks', '0001_initial'),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_refusal', models.DateField()),
                ('operating_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('spare_parts', models.TextField()),
                ('recovery_date', models.DateField()),
                ('equipment_downtime', models.IntegerField()),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.natureoffailure')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machinemodel')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.recoverymethod')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.servicecompany')),
            ],
        ),
    ]
