# Generated by Django 5.0 on 2023-12-24 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaintsmodel_machine'),
        ('machine', '0003_rename_machinemodel_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsmodel',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine'),
        ),
    ]
