# Generated by Django 5.0 on 2023-12-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaints_date_refusal_and_more'),
        ('handbooks', '0003_alter_servicecompany_user'),
        ('machine', '0003_alter_machine_date_shipped_from_factory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complaints',
            new_name='ComplaintsModel',
        ),
    ]
