# Generated by Django 5.0 on 2023-12-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaintsmodel_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsmodel',
            name='operating_time',
            field=models.IntegerField(),
        ),
    ]
