# Generated by Django 5.0 on 2023-12-21 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_rename_complaints_complaintsmodel'),
        ('handbooks', '0009_modelofnodes_modelmachinecomponents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsmodel',
            name='failure_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.modelmachinecomponents'),
        ),
    ]
