# Generated by Django 5.0 on 2023-12-21 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_alter_complaintsmodel_failure_node'),
        ('handbooks', '0009_modelofnodes_modelmachinecomponents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintsmodel',
            name='failure_node',
        ),
        migrations.CreateModel(
            name='ModelOfMachineComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaintsmodel')),
                ('nodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.modelofnodes')),
            ],
        ),
        migrations.AddField(
            model_name='complaintsmodel',
            name='failure_node',
            field=models.ManyToManyField(through='complaints.ModelOfMachineComponents', to='handbooks.modelofnodes'),
        ),
    ]
