# Generated by Django 5.0 on 2023-12-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_remove_complaintsmodel_failure_node_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintsmodel',
            name='failure_node',
        ),
        migrations.DeleteModel(
            name='ModelOfMachineComponents',
        ),
        migrations.AddField(
            model_name='complaintsmodel',
            name='failure_node',
            field=models.CharField(choices=[('EN', 'Двигатель'), ('TR', 'Трансмиссия'), ('DA', 'Ведущий мост'), ('SA', 'Управляемый мост'), ('HY', 'Гидросистема'), ('LD', 'LD')], default='Двигатель', max_length=2),
        ),
    ]
