# Generated by Django 5.0 on 2023-12-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_remove_complaintsmodel_failure_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsmodel',
            name='failure_node',
            field=models.CharField(choices=[('EN', 'Двигатель'), ('TR', 'Трансмиссия'), ('DA', 'Ведущий мост'), ('SA', 'Управляемый мост'), ('HY', 'Гидросистема'), ('LD', 'Подъёмное устройство')], default='Двигатель', max_length=2),
        ),
    ]
