# Generated by Django 5.0 on 2023-12-21 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_alter_complaintsmodel_failure_node'),
        ('handbooks', '0011_delete_modelofnodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsmodel',
            name='failure_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.natureoffailure'),
        ),
    ]
