# Generated by Django 5.0 on 2023-12-13 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handbooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_serial_number', models.TextField(max_length=256)),
                ('engine_serial_number', models.TextField(max_length=256)),
                ('transmission_serial_number', models.TextField(max_length=256)),
                ('drive_axle_serial_number', models.TextField(max_length=256)),
                ('steering_axle_serial_number', models.TextField(max_length=256)),
                ('supply_contract', models.TextField(max_length=256)),
                ('date_shipped_from_factory', models.DateTimeField()),
                ('consignee', models.TextField(max_length=256)),
                ('delivery_address', models.TextField(max_length=256)),
                ('equipment', models.TextField(max_length=256)),
                ('client', models.TextField(max_length=256)),
                ('model_drive_axle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.modelofdriveaxle')),
                ('model_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.modelofengine')),
                ('model_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.modelofequipment')),
                ('model_transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.modeloftransmission')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.servicecompany')),
                ('steering_axle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.modelofsteeringaxle')),
            ],
        ),
    ]
