# Generated by Django 5.0 on 2023-12-24 14:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0002_rename_modelofequipment_machinemodel'),
        ('machine', '0002_rename_model_equipment_machinemodel_machine_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MachineModel',
            new_name='Machine',
        ),
    ]
