# Generated by Django 5.0 on 2023-12-14 09:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_rename_complaints_complaintsmodel'),
        ('handbooks', '0003_alter_servicecompany_user'),
        ('machine', '0003_alter_machine_date_shipped_from_factory'),
        ('maintenance', '0003_remove_maintenance_work_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machine',
            new_name='MachineModel',
        ),
    ]
