# Generated by Django 5.0 on 2023-12-25 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0005_rename_username_client_user'),
        ('machine', '0003_rename_machinemodel_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.client'),
        ),
    ]
