# Generated by Django 5.0 on 2023-12-20 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0006_delete_handbooksmodel'),
        ('machine', '0004_rename_machine_machinemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemodel',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='service_company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='handbooks.servicecompany'),
        ),
    ]
