# Generated by Django 5.0 on 2023-12-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0006_alter_machinemodel_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemodel',
            name='equipment',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
