# Generated by Django 5.0 on 2023-12-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_alter_machine_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='date_shipped_from_factory',
            field=models.DateField(),
        ),
    ]
