# Generated by Django 5.0 on 2023-12-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0001_initial'),
        ('machine', '0002_rename_model_equipment_machinemodel_machine_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelOfEquipment',
            new_name='MachineModel',
        ),
    ]
