# Generated by Django 5.0 on 2023-12-25 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0003_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='username',
        ),
    ]
