# Generated by Django 5.0 on 2023-12-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0003_alter_servicecompany_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandBooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.modelofdriveaxle')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.modelofengine')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.modelofequipment')),
                ('nature_of_failure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.natureoffailure')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.recoverymethod')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.servicecompany')),
                ('steering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.modelofsteeringaxle')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.modeloftransmission')),
                ('type_of_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.typeofmaintenance')),
            ],
        ),
    ]
