# Generated by Django 5.0 on 2023-12-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0005_rename_service_company_handbooksmodel_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HandBooksModel',
        ),
    ]
