# Generated by Django 5.0 on 2023-12-21 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0008_alter_servicecompany_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOfNodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_axle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.modelofdriveaxle')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.modelofengine')),
                ('steering_axle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.modelofsteeringaxle')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.modeloftransmission')),
            ],
        ),
        migrations.CreateModel(
            name='ModelMachineComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.modelofnodes')),
            ],
        ),
    ]
