# Generated by Django 5.0 on 2023-12-21 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_remove_complaintsmodel_failure_node_and_more'),
        ('handbooks', '0009_modelofnodes_modelmachinecomponents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelMachineComponents',
        ),
    ]
