# Generated by Django 5.0 on 2023-12-13 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handbooks', '0001_initial'),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateTimeField()),
                ('operating_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_number', models.TextField(max_length=128)),
                ('order_data', models.DateTimeField()),
                ('work_organization', models.TextField(max_length=256)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.typeofmaintenance')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.servicecompany')),
            ],
        ),
    ]
