# Generated by Django 5.0 on 2023-12-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='order_data',
            field=models.DateField(),
        ),
    ]
