# Generated by Django 5.0 on 2023-12-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenance_maintenance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='work_organization',
        ),
    ]
