# Generated by Django 5.0 on 2023-12-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='date_refusal',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='recovery_date',
            field=models.DateField(),
        ),
    ]
